-- Scope the operational pending queue by carteira so authenticated users can
-- see and handle pending items generated by imports, agreements and messaging.

alter table public.central_pendencias enable row level security;

drop policy if exists central_pendencias_authenticated_all on public.central_pendencias;
drop policy if exists central_pendencias_dev_authenticated_all on public.central_pendencias;
drop policy if exists central_pendencias_carteira_scope_all on public.central_pendencias;

create policy central_pendencias_carteira_scope_all
  on public.central_pendencias
  for all
  to authenticated
  using (
    public.current_user_can_access_carteira(carteira_id)
    or (
      carteira_id is null
      and public.current_user_is_admin()
    )
  )
  with check (
    public.current_user_can_access_carteira(carteira_id)
    or (
      carteira_id is null
      and public.current_user_is_admin()
    )
  );
